# file Makefile
#
CC=pgcc
#CC=gcc
#CC=icc

#CFLAGS =  -Ofast -qopenmp -w3 -diag-disable:remark

ifeq ($(CC),gcc)
	CFLAGS = -O3 -fopenmp -Wall
else
	CFLAGS = -fast -mp -Minfo=all -Mneginfo=all
endif
LDLIBS=-lm
RM= rm -vf

SRCFILES= $(wildcard *.c)
OBJFILES= $(patsubst %.c, %.o, $(SRCFILES))
PROGFILES= $(patsubst %.c, %, $(SRCFILES))

.PHONY: all clean

all: $(PROGFILES)

clean:
	$(RM) $(OBJFILES) $(PROGFILES) *~
## eof Makefile
#pgcc -fast -acc -ta=tesla:managed -Minfo=accel -I/opt/pgi/linux86-64/19.10/mpi/openmpi-3.1.3/include -L/opt/pgi/linux86-64/19.10/mpi/openmpi-3.1.3/lib -lmpi acc_funcoes.c  -o teste
